spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zilongkuaikan?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  mail:
    host: smtp.qq.com
    username: 1819877370@qq.com
    password: aapqgpehglwoedia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qf.pojo

qiniu:
  ak: DbjAKC_dXVPB2B5s7mZiPGO8Dk17bF0sJOrjcJR5
  sk: Om8AZofVZFYZaJo2TMTPMhsWHo0OWqmlNzKmMG37
  bucket: zilongdushu
  url: http://qlfan50gz.hn-bkt.clouddn.com/
#redis配置信息
redis:
  database: 0
  host: 127.0.0.1
#hystirx与feign进行整合
feign:
  hystrix:
    enabled: true

#标注 feign访问接口多少时间没有返回值 报错
#default全局有效，service id指定应用有效
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000

#ribbon的超时时间
ribbon:
 ReadTimeout: 6000
 ConnectTimeout: 6000
